### PR TITLE
Changed Regular Expression

### PR DESCRIPTION
**Pull request by ansraliant**
The regular expression that checks if the file contains #DATA# and #END#, did not work for real life .blm files. 
This PR is the fix to that RE.
Thanks.

### CODE REVIEW

**Comment by stilliard** [comment]
Thanks @ansraliant, 
Do you have an example .blm file where this was needed? as the test one i'd been using was working: https://github.com/stilliard/blmreader/blob/master/tests/test.blm
I can add to the tests then too.

**Comment by ansraliant** [comment]
Hi @stilliard. The test still works with this test file. The thing is that the .blm file I have contains confidential information. What do you suggest I can do?

**Comment by stilliard** [comment]
Ah I see, and you're right the test still works. 
I'll merge this in and I'll look to add some more tests soon to extra safe :)

**Comment by stilliard** [comment]
Thanks for working on this!

**Comment by ansraliant** [comment]
@stilliard thank you for merging :+1:

**Pull request merged**
